### ISSUE TITLE
Possible packaging issue with version 2.0.4

### ISSUE THREAD

**Issue by m-vdb** [Talor-A/react-native-message-bar#16]
Hi there,

First of all thanks so much for maintaining this project. I had started implementing it myself and using this projects seems like a no brainer now.

I installed `2.0.4` version using npm but one feature wasn't working: the ability to set default props on the `<MessageBar />` component. By checking the code on github it should work as expected, but when checking the actual code in my `node_modules/` folder, it looks like at least https://github.com/Talor-A/react-native-message-bar/commit/da9bfc0bbdbccf688874e9d2d428d342a78c275b commit is missing. So I think there was some packaging issue on npm.

**Comment by Talor-A** [comment]
fixed, use version `2.0.6`

**Comment by m-vdb** [comment]
amazing @Talor-A thanks for your rapidity!
