### ISSUE TITLE
Could you tag future releases?

### ISSUE THREAD

**Issue by llamaluvr** [Talor-A/react-native-message-bar#17]
Or maybe you are but I'm missing something in the convention being used. It seems like from package.json, that this is on 2.0.6, but the tags only go up to 1.6.0. It'd help to be to match a release to it's source code when debugging/ considering putting in a pull request.

![screen shot 2017-11-13 at 10 09 32 am](https://user-images.githubusercontent.com/8053974/32732584-0b629eb4-c85b-11e7-8c0d-47f644a61954.png)

Thanks for your work on this awesome package!

**Comment by Talor-A** [comment]
hm, my bad I guess. I thought `npm version` should do this automatically? I'll look into it soon.

**Comment by Talor-A** [comment]
all releases should be tagged now.
