### ISSUE TITLE
MessageBar disappears even though shouldHideAfterDelay property is set to false

### ISSUE THREAD

**Issue by atandonquickbase** [Talor-A/react-native-message-bar#20]
<img width="251" alt="screen shot 2017-11-17 at 1 22 34 pm" src="https://user-images.githubusercontent.com/29211408/32962446-753dcc72-cb9a-11e7-845e-cf74d154cded.png">
Am I missing out on something?

**Comment by aksonov** [comment]
The same issue. Any response?

**Comment by atandonquickbase** [comment]
In MessageBar.js, there is following code snippet
<img width="389" alt="screen shot 2017-11-29 at 12 43 30 pm" src="https://user-images.githubusercontent.com/29211408/33390113-f6fa802c-d502-11e7-97a4-41e1f0f692f1.png">
Doing the '&&' check might solve the problem

**Comment by atandonquickbase** [comment]
@Talor-A Could you please have a look?

**Comment by Talor-A** [comment]
I'll check this out tomorrow.

**Comment by Talor-A** [comment]
fixed in `v2.0.7`. not sure why this stopped working initially, thanks for reporting it.

**Comment by atandonquickbase** [comment]
shouldHideOnTap should also have the same fix. What do you think ?

**Comment by atandonquickbase** [comment]
And Thanks for looking into it

**Comment by itcurves** [comment]
not working for me ver: 2.0.10
