### ISSUE TITLE
Titlestyle and messageStyle is not applying

### ISSUE THREAD

**Issue by mkayswork** [Talor-A/react-native-message-bar#21]
Hi there,

first of all thank you for keeping the maintenance of this project! 👍 

What I discovered is that the styling for the title and the message is not working properly. I am using this method call to have a white message and title, but still it's not working. I also tried not to provide any color since the default value is white.

Here's the method:

`MessageBarManager.showAlert({
          title: 'Teilen nicht möglich',
          message: 'Die zugehörige App ist nicht installiert!',
          alertType: 'info',
          stylesheetInfo: { backgroundColor: Constants.APP_COLOR, },
          titleStyle: { color: '#fff' },
          messageStyle: {color: '#fff', fontFamily: Constants.FONT_DEFAULT},
          duration: 3000
        })`

Any idea what might be causing this issue?

**Comment by Talor-A** [comment]
thanks for reporting this. it looks like providing the `stylesheetInfo` prop causes the other styles to be overridden. as a workaround, can you do `stylesheetInfo:{ backgroundColor:Constants.APP_COLOR, strokeColor: Constants.APP_COLOR, titleColor:'#fff', messageColor: '#fff'}` ?

**Comment by mkayswork** [comment]
Thanks for the response. I made it work only using the prop stylesheetExtra without specifiying titleStyle or messageStyle
