### ISSUE TITLE
Can only Update a mounting and mounted component

### ISSUE THREAD

**Issue by lgupta54** [Talor-A/react-native-message-bar#22]
**Issue**: Can only Update a mounting and mounted component. This usually means you called setState or the forceUpdate on the unmounted component. This is a no-op.
Please check the code for the  MessageBar Component.

Registered and unregistered MessageBarManager as is it is shown in demo. But when coming back from navigated screen, this warning shows up and Alert message does not shows then.

**Comment by Talor-A** [comment]
this is a problem with react-navigation, not this library. screens aren't unmounted when navigating away from them. to fix this put your message bar component outside of the stacknavigator component.

**Comment by malonguwa** [comment]
@Talor-A Could you mind to give a example about outside of stacknavigator component?
Cos my app is using StackNavigator at App.js as the root component, 

App.js
......
    render() {
            return <LoginStackNavigator screenProps={screenProps} />;
    }
How to put message bar component outside of the stacknavigator ? 

Thanks a lot

**Comment by malonguwa** [comment]
I fix it~ Thanks @Talor-A , I think I got what you mean~

I solved it by doing this,
in App.js
```
 render() {
            return <View style={{flex:1, backgroundColor:"green"}}>
                <LoginStackNavigator screenProps={screenProps} />
                <MessageBarAlert ref="alertLogin"/>
            </View>;
}
```
