### ISSUE TITLE
undefined: this_currentMessageBarAlert.hideMessageBarAlert 

### ISSUE THREAD

**Issue by ikendoit** [Talor-A/react-native-message-bar#24]
Hello, I was trying out the message bar and i get this error : 

![screenshot_1514530068](https://user-images.githubusercontent.com/26758925/34431262-79c6686e-ec22-11e7-8997-b73cb07cbd3b.png)

my testMess(): 
```
66.  testMess(){
  67.	MessageBarManager.showAlert({
		title: "title jere", 
		message: "a message for a message", 
		alertType: "success",
	});
	console.log("did a message show ??? ");
  }

```

My ComponentDidMount: 
```
  componentDidMount() {
    this.setState({
      ..........
    });
    MessageBarManager.registerMessageBar(this.refs.alert);
    this.testMess();
  }
```
I set up everything as told in the manual but this didn't work.
Has anyone had this problem before ? i tried playing around with the MessageBarManager.js but nothing worked.

**Comment by hamidfzm** [comment]
I have the same problem. I think alert reference register has problem.

**Comment by Talor-A** [comment]
are you sure that `this.refs.alert` is != `undefined`? that's the only way I can see this error happening.

**Comment by hamidfzm** [comment]
I think it is a binding problem. I used https://github.com/Qlean/react-native-messages. It's a simple message bar (So simple compared to this project) but they implemented a better code( or binding solution) for message bar manager. Please take a look at their source code.

**Comment by ugendrang** [comment]
+1

**Comment by Talor-A** [comment]
@hamidfzm thanks for showing me that library, it's definitely a better solution. I unfortunately don't have the time to do any major refactoring of this library right now, but I'll look into this issue again. unfortunately so far I haven't been able to reproduce the problem, but if anyone wants to share a simple demo project I'll take a look.

**Comment by ikendoit** [comment]
Thank you @blntylmn , the way you used setTimeout was very clever ! I will surely try it your way.

**Comment by thisdotvoid** [comment]
You can just register in ref callback:
```jsx
<MessageBar
  ref={ref => {
    MessageBarManager.registerMessageBar(ref);
  }}
/>
```

**Comment by phillbaker** [comment]
This seems similar to the upstream issue: https://github.com/KBLNY/react-native-message-bar/issues/46
