### ISSUE TITLE
The bar appears behind the title

### ISSUE THREAD

**Issue by NdozHH** [Talor-A/react-native-message-bar#26]
The bar appears behind the title.

![image](https://user-images.githubusercontent.com/25773289/35242957-3e098d40-ff89-11e7-9622-e41c20841552.png)

**Comment by Talor-A** [comment]
im sorry what title? this looks like a problem with your layout and not the message bar. make sure it's after any other elements in your JSX.

**Comment by Frank17** [comment]
if the bar is placed after listview, it would show at the bottom of the window
if it is placed before listview, it will show behind the list, how can I get solution?

**Comment by Talor-A** [comment]
check the instructions in the README. if the bar is the last JSX element in your root `View` component it will not show up at the bottom of the window or be covered by elements.
