### ISSUE TITLE
Compatibility with RN Modal

### ISSUE THREAD

**Issue by Xyzor** [Talor-A/react-native-message-bar#27]
Hello!

I'm curious if it's possible to show the message bar on top of an open modal component?

The modal component: https://facebook.github.io/react-native/docs/modal.html

**Comment by Xyzor** [comment]
I created a demo, to demonstrate the problem.
Out of the box, this modul is not compatible with modal.

[Demo](https://snack.expo.io/@xyzor/modal-and-message-bar-compatibility-issue-demo)

Steps to reproduce the issue:
1. Click on 'Open modal'
2. Click on 'Show message' (notice, that nothing happens)
3. Click on 'Close modal' (you can see that the message bar is under the modal)

**Comment by Talor-A** [comment]
If I remember correctly the react native modal is a native component that opens a new view on top of the current react native view. I'd recommend a JS based solution for your modal instead.
