### ISSUE TITLE
How to use this globally?

### ISSUE THREAD

**Issue by bonbonio** [Talor-A/react-native-message-bar#29]
Hello,

Does anyone use this by having the component in the main App root component, and then just sending the errors from elsewhere in the App, rather than the component needing added to all screens...

I understand it makes a dependency, but just wondering what patterns people use to avoid duplication.

**Comment by Talor-A** [comment]
you should only need one message bar, not one for each screen. I will reopen this issue if you're having trouble.

**Comment by chandanrai95** [comment]
How to update the context of message bar for each screen
