### ISSUE TITLE
Styling issue in success bar

### ISSUE THREAD

**Issue by xavimb** [Talor-A/react-native-message-bar#6]
Hello! First of all thanks for maintaining this library.

I found one styling issue in the success alert. There's a very annoying red bar at the bottom of the alert. I've tried to remove it with custom styles but it fix the problem.

<img width="548" alt="screen shot 2017-07-10 at 23 34 36" src="https://user-images.githubusercontent.com/1402224/28038909-22f66e24-65c9-11e7-8a66-503fbe6c0416.png">

**Comment by Talor-A** [comment]
@xavimb is the issue fixed for you now? You might need to npm reinstall.

**Comment by xavimb** [comment]
Yes, it's working now. Thanks!
