### ISSUE TITLE
delay before message bar appears

### ISSUE THREAD

**Issue by Talor-A** [Talor-A/react-native-message-bar#8]
Original Issue [here](https://github.com/KBLNY/react-native-message-bar/issues/33).

**Comment by gyfis** [comment]
It would seem that the delay is caused by the alert hiding system which does not properly recognize if there is an alert shown or not. Plus there's an additional 100ms delay.

**Comment by rochapablo** [comment]
The delay still on version ``` 2.0.6```

**Comment by raghudevan** [comment]
I'm seeing a lot of delay on android; 20+ seconds for the alert to show up (This is on Android)

**Comment by Talor-A** [comment]
I'm not able to reproduce this @rochapablo @raghudevan , please post sample code or send a PR.

**Comment by malonguwa** [comment]
@Talor-A Thanks for maintain this lovely message bar, I try to use it in my project, but it is seems not work for my Android Emulator Pixel_API_26:5554 which comes with the Android Studio. But it is perfectly working in iOS Simulator. I do not have any Android phone at the moment, so I can not test it on real phone.

my implementation code is really simple (Not using redux in my project).

```
let MessageBarAlert = require('react-native-message-bar').MessageBar;
let MessageBarManager = require('react-native-message-bar').MessageBarManager;

    componentDidMount() {
        MessageBarManager.registerMessageBar(this.refs.alert);
    }

    componentWillUnmount() {
        MessageBarManager.unregisterMessageBar();
    }

    _navigateToMainTabScreen = () => {
        this.dismissSystemKeyboard();
        if (this.fieldsValidator() === true) {
           // switch to mainTab screen
        } else {
            MessageBarManager.showAlert({
                title: 'Missing field',
                message: 'Please fill in both fields in order to login',
                alertType: 'error',
                viewTopInset: 8,
            })
        }
    };
    render() {
        return (
            <View>
             ..........
                           <MessageBarAlert ref="alert" />
            </View>
     }
```

**Comment by Talor-A** [comment]
hm, strange that it wasn't working on the android emulator. there's no native code, so everything should be the same. glad to see it's alright now. going to close this, I'll reopen if someone else has the same issue.
